### ISSUE TITLE
Don't open app macos

### ISSUE THREAD

**Issue by devbedirhangul** [goldtokensa/ocean-wallet#2]

**Comment by vysegrad** [comment]
@tomt1664 the latest wallet doesn't work on Mac OSX. Will there be a fix?

**Comment by vysegrad** [comment]
@tomt1664 

Errors in latest mac osx version. Note that the latest wallet doesn't even start so i had to use and older build. Can this be fixed please?

![SAVE_20201130_084542](https://user-images.githubusercontent.com/74591866/100582330-6351b500-32e9-11eb-826d-dc83a06b4cdf.jpg)
![SAVE_20201130_084548](https://user-images.githubusercontent.com/74591866/100582334-6482e200-32e9-11eb-8eb2-b391f086048d.jpg)

**Comment by tomt1664** [comment]
The recent MacOS release (11.0 Big Sur) caused a problem with the GUI engine (PyQt). We are building a new version that will work with Big Sur which will be released shortly.

**Comment by vysegrad** [comment]
@tomt1664 is there a release date for the Mac OS wallet yet?

**Comment by tomt1664** [comment]
Hi, 
Sorry for the delay. A new version of the wallet that is compatible with Big Sur has been added to the latest release: https://github.com/goldtokensa/ocean-wallet/releases/tag/1.0.3
