### ISSUE TITLE
gold_main seed nodes are missing or outdated

### ISSUE THREAD

**Issue by Sjors** [goldtokensa/ocean-wallet#3]
Using `oceand -chain=gold_main` compiled from source (`v2.1.1.1-7c11ad9ca`) there are no DNS seeds and either no fixed seed nodes or none of them are reachable. So it doesn't sync.

**Comment by Sjors** [comment]
Mmm, I guess you also need this: https://github.com/goldtokensa/config/blob/master/mainnet/ocean/ocean.conf (minus the rpc lines)

But I'm still missing something. The [README](https://github.com/goldtokensa/config#dgld-configuration) of that repo says the gensis hash should be `c66cb6eb7cd585788b294be28c8dcd6be4e37a0a6d238236b11c0beb25833bb9`, but my node says its `900959e177c9a1a3fa7f100ee978c66c2e39ba546b44157127f912a750dec83d`. And then of course it complains when receiving headers `ERROR: AcceptBlockHeader: prev block not found`.

I notice the above document is referring to a client version 2.1.7, whereas this repo is at 2.1.1, so I'm guessing this repo is outdated?

**Comment by Sjors** [comment]
Wait, I opened this on the wrong repo, will reopen.

**Comment by tomt1664** [comment]
You also need the directory `terms-and-conditions/gold_main` and the two files within, in the same directory as the `ocean.conf`.

**Comment by Sjors** [comment]
That's a bit weird, but it works!
